package com.zys.myspringboot.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.id
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.title
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.gmt_create
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.gmt_modified
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.creator
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.comment_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.view_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.like_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.tag
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.description
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.id
     *
     * @return the value of QUESTION.id
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.id
     *
     * @param id the value for QUESTION.id
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.title
     *
     * @return the value of QUESTION.title
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.title
     *
     * @param title the value for QUESTION.title
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.gmt_create
     *
     * @return the value of QUESTION.gmt_create
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.gmt_create
     *
     * @param gmtCreate the value for QUESTION.gmt_create
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.gmt_modified
     *
     * @return the value of QUESTION.gmt_modified
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.gmt_modified
     *
     * @param gmtModified the value for QUESTION.gmt_modified
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.creator
     *
     * @return the value of QUESTION.creator
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.creator
     *
     * @param creator the value for QUESTION.creator
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.comment_count
     *
     * @return the value of QUESTION.comment_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.comment_count
     *
     * @param commentCount the value for QUESTION.comment_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.view_count
     *
     * @return the value of QUESTION.view_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.view_count
     *
     * @param viewCount the value for QUESTION.view_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.like_count
     *
     * @return the value of QUESTION.like_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.like_count
     *
     * @param likeCount the value for QUESTION.like_count
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.tag
     *
     * @return the value of QUESTION.tag
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.tag
     *
     * @param tag the value for QUESTION.tag
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.description
     *
     * @return the value of QUESTION.description
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.description
     *
     * @param description the value for QUESTION.description
     *
     * @mbg.generated Tue Mar 21 22:41:59 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}