package com.zys.myspringboot.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.ID
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.ACCOUNT_ID
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.NAME
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.TOKEN
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.GMT_CREATE
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.GMT_MODIFIED
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.AC_TOKEN
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private String acToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.BIO
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NAME.avatar_url
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.ID
     *
     * @return the value of USER_NAME.ID
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.ID
     *
     * @param id the value for USER_NAME.ID
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.ACCOUNT_ID
     *
     * @return the value of USER_NAME.ACCOUNT_ID
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.ACCOUNT_ID
     *
     * @param accountId the value for USER_NAME.ACCOUNT_ID
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.NAME
     *
     * @return the value of USER_NAME.NAME
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.NAME
     *
     * @param name the value for USER_NAME.NAME
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.TOKEN
     *
     * @return the value of USER_NAME.TOKEN
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.TOKEN
     *
     * @param token the value for USER_NAME.TOKEN
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.GMT_CREATE
     *
     * @return the value of USER_NAME.GMT_CREATE
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.GMT_CREATE
     *
     * @param gmtCreate the value for USER_NAME.GMT_CREATE
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.GMT_MODIFIED
     *
     * @return the value of USER_NAME.GMT_MODIFIED
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.GMT_MODIFIED
     *
     * @param gmtModified the value for USER_NAME.GMT_MODIFIED
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.AC_TOKEN
     *
     * @return the value of USER_NAME.AC_TOKEN
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public String getAcToken() {
        return acToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.AC_TOKEN
     *
     * @param acToken the value for USER_NAME.AC_TOKEN
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setAcToken(String acToken) {
        this.acToken = acToken == null ? null : acToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.BIO
     *
     * @return the value of USER_NAME.BIO
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.BIO
     *
     * @param bio the value for USER_NAME.BIO
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_NAME.avatar_url
     *
     * @return the value of USER_NAME.avatar_url
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_NAME.avatar_url
     *
     * @param avatarUrl the value for USER_NAME.avatar_url
     *
     * @mbg.generated Wed Mar 22 03:44:57 CST 2023
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}