package com.zys.myspringboot.mapper;

import com.zys.myspringboot.dto.QuestionQueryDTO;
import com.zys.myspringboot.model.Question;

import java.util.List;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Sun Feb 26 14:50:13 CST 2023
     */
    int incView(Question row);
    int incCommentCount(Question row);

    List<Question> selectRelated(Question question);

    Integer countBySearch(QuestionQueryDTO questionQueryDTO);

    List<Question> selectBySearch(QuestionQueryDTO questionQueryDTO);
}